# Configuration file for Instagram account generator

# General settings - required
account_amount = 2  # Number of accounts to generate

# Email agent settings - required
email_agent = "10minemail"  # The email agent to generate a disposable email

# Proxy settings - optional
# proxy_path = "/path/to/proxy-list.txt"
